// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/verify-otp": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/workspace": {
    params: {};
  };
  "/meetings": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/administration": {
    params: {};
  };
  "/administration/role-management": {
    params: {};
  };
  "/administration/user-management": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/tasks": {
    params: {};
  };
  "/members": {
    params: {};
  };
  "/archived": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/project/:id": {
    params: {
      "id": string;
    };
  };
  "/task/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/verify-otp" | "/forgot-password" | "/reset-password" | "/verify-email" | "/dashboard" | "/workspace" | "/meetings" | "/messages" | "/administration" | "/administration/role-management" | "/administration/user-management" | "/profile" | "/tasks" | "/members" | "/archived" | "/settings" | "/project/:id" | "/task/:id" | "/*";
  };
  "routes/auth/auth-layout.tsx": {
    id: "routes/auth/auth-layout";
    page: "/" | "/sign-in" | "/sign-up" | "/verify-otp" | "/forgot-password" | "/reset-password" | "/verify-email";
  };
  "routes/root/home.tsx": {
    id: "routes/root/home";
    page: "/";
  };
  "routes/auth/sign-in.tsx": {
    id: "routes/auth/sign-in";
    page: "/sign-in";
  };
  "routes/auth/sign-up.tsx": {
    id: "routes/auth/sign-up";
    page: "/sign-up";
  };
  "routes/auth/verify-otp.tsx": {
    id: "routes/auth/verify-otp";
    page: "/verify-otp";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "components/layout/dashboard-layout.tsx": {
    id: "components/layout/dashboard-layout";
    page: "/dashboard" | "/workspace" | "/meetings" | "/messages" | "/administration" | "/administration/role-management" | "/administration/user-management" | "/profile" | "/tasks" | "/members" | "/archived" | "/settings" | "/project/:id" | "/task/:id";
  };
  "routes/dashboard/dashboard.tsx": {
    id: "routes/dashboard/dashboard";
    page: "/dashboard";
  };
  "routes/workspace/workspace.tsx": {
    id: "routes/workspace/workspace";
    page: "/workspace";
  };
  "routes/meetings/meetings.tsx": {
    id: "routes/meetings/meetings";
    page: "/meetings";
  };
  "routes/messages/messages.tsx": {
    id: "routes/messages/messages";
    page: "/messages";
  };
  "routes/administration/administration.tsx": {
    id: "routes/administration/administration";
    page: "/administration";
  };
  "routes/administration/role-management/role-management.tsx": {
    id: "routes/administration/role-management/role-management";
    page: "/administration/role-management";
  };
  "routes/administration/user-management/user-management.tsx": {
    id: "routes/administration/user-management/user-management";
    page: "/administration/user-management";
  };
  "routes/profile/profile.tsx": {
    id: "routes/profile/profile";
    page: "/profile";
  };
  "routes/tasks/tasks.tsx": {
    id: "routes/tasks/tasks";
    page: "/tasks";
  };
  "routes/members/members.tsx": {
    id: "routes/members/members";
    page: "/members";
  };
  "routes/archived/archived.tsx": {
    id: "routes/archived/archived";
    page: "/archived";
  };
  "routes/settings/settings.tsx": {
    id: "routes/settings/settings";
    page: "/settings";
  };
  "routes/project/project-detail.tsx": {
    id: "routes/project/project-detail";
    page: "/project/:id";
  };
  "routes/task/task-detail.tsx": {
    id: "routes/task/task-detail";
    page: "/task/:id";
  };
  "routes/root/not-found.tsx": {
    id: "routes/root/not-found";
    page: "/*";
  };
};