// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/verify-otp": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/workspace": {
    params: {};
  };
  "/tasks": {
    params: {};
  };
  "/meetings": {
    params: {};
  };
  "/members": {
    params: {};
  };
  "/archived": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/project/:id": {
    params: {
      "id": string;
    };
  };
  "/task/:id": {
    params: {
      "id": string;
    };
  };
  "/analytics": {
    params: {};
  };
  "/analytics/workspace": {
    params: {};
  };
  "/analytics/leaderboard": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/verify-otp" | "/forgot-password" | "/reset-password" | "/verify-email" | "/dashboard" | "/workspace" | "/tasks" | "/meetings" | "/members" | "/archived" | "/chat" | "/settings" | "/project/:id" | "/task/:id" | "/analytics" | "/analytics/workspace" | "/analytics/leaderboard" | "/*";
  };
  "routes/root/redirect.tsx": {
    id: "routes/root/redirect";
    page: "/";
  };
  "routes/auth/auth-layout.tsx": {
    id: "routes/auth/auth-layout";
    page: "/sign-in" | "/sign-up" | "/verify-otp" | "/forgot-password" | "/reset-password" | "/verify-email";
  };
  "routes/auth/sign-in.tsx": {
    id: "routes/auth/sign-in";
    page: "/sign-in";
  };
  "routes/auth/sign-up.tsx": {
    id: "routes/auth/sign-up";
    page: "/sign-up";
  };
  "routes/auth/verify-otp.tsx": {
    id: "routes/auth/verify-otp";
    page: "/verify-otp";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "components/layout/dashboard-layout.tsx": {
    id: "components/layout/dashboard-layout";
    page: "/dashboard" | "/workspace" | "/tasks" | "/meetings" | "/members" | "/archived" | "/chat" | "/settings" | "/project/:id" | "/task/:id" | "/analytics" | "/analytics/workspace" | "/analytics/leaderboard";
  };
  "routes/dashboard/dashboard.tsx": {
    id: "routes/dashboard/dashboard";
    page: "/dashboard";
  };
  "routes/workspace/workspace.tsx": {
    id: "routes/workspace/workspace";
    page: "/workspace";
  };
  "routes/tasks/tasks.tsx": {
    id: "routes/tasks/tasks";
    page: "/tasks";
  };
  "routes/meetings/meetings.tsx": {
    id: "routes/meetings/meetings";
    page: "/meetings";
  };
  "routes/members/members.tsx": {
    id: "routes/members/members";
    page: "/members";
  };
  "routes/archived/archived.tsx": {
    id: "routes/archived/archived";
    page: "/archived";
  };
  "routes/chat/chat.tsx": {
    id: "routes/chat/chat";
    page: "/chat";
  };
  "routes/settings/settings.tsx": {
    id: "routes/settings/settings";
    page: "/settings";
  };
  "routes/project/project-detail.tsx": {
    id: "routes/project/project-detail";
    page: "/project/:id";
  };
  "routes/task/task-detail.tsx": {
    id: "routes/task/task-detail";
    page: "/task/:id";
  };
  "routes/analytics/analytics.tsx": {
    id: "routes/analytics/analytics";
    page: "/analytics" | "/analytics/workspace" | "/analytics/leaderboard";
  };
  "routes/analytics/performance.tsx": {
    id: "routes/analytics/performance";
    page: "/analytics";
  };
  "routes/analytics/workspace.tsx": {
    id: "routes/analytics/workspace";
    page: "/analytics/workspace";
  };
  "routes/analytics/leaderboard.tsx": {
    id: "routes/analytics/leaderboard";
    page: "/analytics/leaderboard";
  };
  "routes/root/not-found.tsx": {
    id: "routes/root/not-found";
    page: "/*";
  };
};